{
 "title": "Todo App Observability",
 "tags": [
  "todo",
  "devops"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Requests per Minute",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"app\",service=\"backend\"}[5m]))",
     "legendFormat": "error_rate"
    }
   ]
  },
  {
   "title": "5xx Error Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"app\",service=\"backend\",status_code=~\"5..\"}[5m])) / sum(rate(http_requests_total{namespace=\"app\",service=\"backend\"}[5m]))",
     "legendFormat": "error_rate"
    }
   ]
  },
  {
   "title": "Average Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{namespace=\"app\",service=\"backend\"}[5m]))\r\n /\r\nsum(rate(http_request_duration_seconds_count{namespace=\"app\",service=\"backend\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"app\",service=\"backend\"}[5m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Requests by Route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"app\",service=\"backend\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Frontend Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"frontend\"} |= ``"
    }
   ]
  },
  {
   "title": "Backend Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"backend\"} |= ``"
    }
   ]
  }
 ]
}